# Generated by Django 3.2.2 on 2021-05-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media/')),
                ('result', models.CharField(choices=[('Fair', 'Fair'), ('Mild', 'Mild'), ('Dark', 'Dark')], max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
